name: Project Flask Task
on:
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute test
        run: python -m pytest --cov-report=xml --cov=.

  validate_pull_request:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: python -m pytest --cov-report=xml --cov=.
      
    - name: Install xmlstarlet
      run: sudo apt-get update && sudo apt-get install -y xmlstarlet
      
    - name: Calculate coverage percentage
      id: calculate_coverage
      run: |
        coverage xml
        total_lines=$(xmlstarlet sel -t -v "count(//line)" coverage.xml)
        covered_lines=$(xmlstarlet sel -t -v "count(//line[@hits!=0])" coverage.xml)
        coverage_percent=$(( 100 * covered_lines / total_lines ))
        echo "::set-output name=coverage_percent::$coverage_percent"

    - name: Check coverage percentage
      run: |
        if [[ "${{ steps.calculate_coverage.outputs.coverage_percent }}" -lt ${{ env.MIN_COVERAGE_PERCENT }} ]]; then
          echo "Error: Test coverage percentage is below threshold (${{ env.MIN_COVERAGE_PERCENT }}%)"
          exit 1
        fi

env:
  MIN_COVERAGE_PERCENT: 60