name: Project Flask Task
on:
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.3"
      - name: Install Dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
      - name: Test
        run: python -m pytest
